### ISSUE TITLE
poll_thread indefinitely waits for a new event

### ISSUE THREAD

**Issue by koleini** [mirage/mirage-net-xen#15] opened 2014-12-29 15:47 UTC
in netif.ml, function poll_thread (line 309):

If rx_poll releases all grefs granted in refill_requests function (line 311), then Activations.after will wait for a new event indefinitely.

A quick fix would be to swap the lines

rx_poll nf.t nf.receive_callback; (line 312)

and 

lwt () = refill_requests nf.t in (line 311)

**Comment by mor1** [comment] 2015-01-01 20:08
(possibly a little context would help here -- which files, lines, etc.)

**Comment by koleini** [comment] 2015-01-02 09:54
Updated.

**Comment by talex5** [comment] 2015-01-14 20:05
So, if I understand you (and this code) correctly:

1. netback signals us because it has filled in some pages we shared with it
2. we check for free space, sharing new empty pages to receive more data for any free slots
3. we process the filled-in pages, which frees up more slots
4. we go to sleep waiting for another event

This is wrong, because we don't provide new pages for the slots we freed this time around the loop. And if all the slots are freed in one go, then we won't share any pages and so no more data can be received.

If so, your "quick fix" sounds right to me, but I don't know much about this code.

**Comment by koleini** [comment] 2015-01-16 09:51
Correct. If in (1), netback has filled in all the pages, then (2) doesn't find any free slots and shares no empty pages with netback and therefore (4) doesn't receive events any more.

**Comment by djs55** [comment] 2015-01-16 15:33
I suspect we should keep running round and round the loop while we still
have work to do and only go to sleep if we have definitely run out. IIRC
peers are supposed to check for work before going to sleep and the other
end can avoid sending us unnecessary interrupts when they can tell (e.g.
via the ring event counters) that we're going to poll at least once more.


On Fri, Jan 16, 2015 at 9:51 AM, Masoud Koleini <notifications@github.com>
wrote:

> Correct. If in (1), netback has filled in all the pages, then (2) doesn't
> find any free slots and shares no empty pages with netback and therefore
> (4) doesn't receive events any more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-net-xen/issues/15#issuecomment-70230864>
> .
>



-- 
Dave Scott

**Comment by avsm** [comment] 2015-01-24 10:41
@djs55 yes, that's the correct analysis I think.  Since netfront can't use Ring directly (due to having two rings and one event channel), we manually call Activations instead.  I think the polling loop should be checking for work in *both* the tx and rx rings before dropping into the Activations wait.

Is this something that can be worked into your refactoring?  I'm going to apply the quick fix first, but we also need to ensure that ring starvation doesn't occur from (e.g.) polling just the tx ring without dropping into the scheduler to let the rx ring also see some CPU.  Not getting this right will probably stall TCP throughput since it's quite sensitive to packet pacing on both TX and RX (since acks flow in both directions).

**Comment by djs55** [comment] 2015-01-24 13:56
I'll see what I can do with the refactoring -- currently I'm testing my
netback + netfront combination by pumping data through the same way the
vchan tests do it. Needless to say I've got plenty of debugging to do there
(problems caused by the refactoring itself) but I'd like to see if I could
make it reliably tickle edge-cases like this too.


On Sat, Jan 24, 2015 at 10:41 AM, Anil Madhavapeddy <
notifications@github.com> wrote:

> @djs55 <https://github.com/djs55> yes, that's the correct analysis I
> think. Since netfront can't use Ring directly (due to having two rings and
> one event channel), we manually call Activations instead. I think the
> polling loop should be checking for work in *both* the tx and rx rings
> before dropping into the Activations wait.
>
> Is this something that can be worked into your refactoring? I'm going to
> apply the quick fix first, but we also need to ensure that ring starvation
> doesn't occur from (e.g.) polling just the tx ring without dropping into
> the scheduler to let the rx ring also see some CPU. Not getting this right
> will probably stall TCP throughput since it's quite sensitive to packet
> pacing on both TX and RX (since acks flow in both directions).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-net-xen/issues/15#issuecomment-71310232>
> .
>



-- 
Dave Scott

**Comment by talex5** [comment] 2016-05-04 18:32
This was fixed in https://github.com/avsm/mirage-net-xen/commit/d43ea46c7aff9a95d2c29b7c1ddb57e90b01a3be so closing. Will open a new issue for tests.

**Closed by talex5** 2016-05-04 18:32 UTC
